// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAz2iYvwuaywNmy0XWPIi0pCS7mmQ26tf8',
    appId: '1:89932927252:web:226684faceafde0bcfb201',
    messagingSenderId: '89932927252',
    projectId: 'hackerrank-1278b',
    authDomain: 'hackerrank-1278b.firebaseapp.com',
    storageBucket: 'hackerrank-1278b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUeQs4oA--RU6YcRweGJStv3kq_4cpv2o',
    appId: '1:89932927252:android:084e66c0b66766afcfb201',
    messagingSenderId: '89932927252',
    projectId: 'hackerrank-1278b',
    storageBucket: 'hackerrank-1278b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqBuuNCBJD0HBFiMcgfONSeDp78secUIg',
    appId: '1:89932927252:ios:386964078852832dcfb201',
    messagingSenderId: '89932927252',
    projectId: 'hackerrank-1278b',
    storageBucket: 'hackerrank-1278b.appspot.com',
    iosBundleId: 'com.example.hackerRank',
  );
}
